### ISSUE TITLE
Runtime Error While Downloading Images.

### ISSUE THREAD

**Issue by m0mosenpai** [anshuman73/xkcd-scraper#6] opened 2017-11-23 16:57 UTC
https://imgur.com/a/9Arqe

Here is the screenshot of the execution of the program in Terminal on Linux.
Not sure if it should be that way (i hope not).

**Comment by anshuman73** [comment] 2017-11-23 17:23
Hi @MomoSenpai07 
This script it pretty much unmaintained. I wrote this at a time I was starting out programming and testing new and fun stuff, so it doesn't exactly handle errors like a boss.
If you look at the tracebacks, the cause of the error is simple. The image it tries to download (1884) contains a slash ("/") in it's name, hence when retrieving it via urlretrieve(), the file system takes that / to be a part of the file. This is a simple case of not escaping such chars in the filename. If I remember correctly, I made a stupid function in another of my scrapers which used to simplly remove such chars from the filename.
The repository is under MIT license so feel free to fork and make the improvements you'd like :) Also feel free to submit a PR if you're interested to !

Let me know if you need more help with this, I'm closing the issue as of now as I am currently not interested in maintaining the project :)

**Closed as completed by anshuman73** 2017-11-23 17:23 UTC

**Comment by m0mosenpai** [comment] 2017-11-23 17:33
@anshuman73 
Yeah that makes sense. Not the right place to post such comments, but any way to contact you for future issues/discussion on projects and stuff? Email maybe?

**Comment by anshuman73** [comment] 2017-11-23 17:43
Nah, this is the perfect place for such issues. Hence "Issues"

**Comment by anshuman73** [comment] 2017-11-23 17:46
Also, if you're interested, I'd suggest looking into Python 3's async features and using the requests library. They're probably much better than urllib. Also, iirc, there's a grequests library which allows async requests using gevent, so maybe look into that too for a better performance.

**Comment by m0mosenpai** [comment] 2017-11-23 18:19
Will look into those for sure. I'm not familiar with Python as of now but i do plan to delve into it in the near future. I also ran a few other scripts of yours . Was interested in XKCD and Cyanide And Happiness so your scripts seemed like the perfect way to go. Unfortunately , there were a few bugs in the xplosm-scraper as well (You're not interested in that project too as of now i'm guessing. ) Maybe i'll improve upon those scripts sometime. Nice content btw.
